title: Siyoung Choi
logo: /assets/img/sychoi_itaewon.jpg
description: <p><b>Ph. D. candidate </b><br>Department of ECE, SNU, Seoul, Korea</p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
